const data= {
    products:[
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            slug: 'FreeShirt',
            description: 'A popular Shirt',
        },
        {
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
            slug: 'FitShirt',
            description: 'A popular fit Shirt',
        },
        {
            name: 'Slim Pant',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            slug: 'SlimPant',
            description: 'A popular slim pant',
        },
        {
            name: 'Dark Pant',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            slug: 'DarkPant',
            description: 'A popular pant',
        },
        {
            name: 'Dark Shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            slug: 'DarkShirt',
            description: 'A popular shirt',
        },
        {
            name: 'Darker Pant',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price:70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            slug: 'DarkerPant',
            description: 'A popular pant',
        },
        
    ]
}

export default data