import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
            <div>
              <h1 className='text-3xl font-bold .bg-blue-50'>Hello</h1>
            </div>
        </Layout>
      </div>
    </div>
  )
}
